name: clang-format Check
on:
  pull_request:
    branches:
      - '**'
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'plugins'
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v3.2.0
      with:
        clang-format-version: '11'
        check-path: ${{ matrix.path }}